# Generated by Django 4.2.6 on 2023-10-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=6)),
                ('DOB', models.CharField(max_length=50)),
                ('passwords', models.CharField(default=' ', max_length=10000000)),
            ],
        ),
    ]
