# Generated by Django 4.2.6 on 2023-10-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='name',
            new_name='uname',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='phone',
        ),
        migrations.AlterField(
            model_name='signup',
            name='passwords',
            field=models.CharField(default='', max_length=10000000),
        ),
    ]
