# Generated by Django 4.2.6 on 2023-10-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_signup_uname_remove_signup_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='passwords',
            field=models.CharField(default="{'facebook':'none','instagram':'none','twitter':'none','spotify':'none','dropbox':'none','google':'none'}", max_length=10000000),
        ),
    ]
