# Generated by Django 4.2.6 on 2023-10-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_signup_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='passwords',
            field=models.CharField(default="{'facebook':None,'instagram':None,'twitter':None,'spotify':None,'dropbox':None,'google':None}", max_length=10000000),
        ),
    ]
