# Generated by Django 4.2.6 on 2023-10-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_signup_key_alter_signup_passwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='key',
        ),
        migrations.AlterField(
            model_name='signup',
            name='passwords',
            field=models.CharField(default='eydmYWNlYm9vayc6Tm9uZSwnaW5zdGFncmFtJzpOb25lLCd0d2l0dGVyJzpOb25lLCdzcG90aWZ5JzpOb25lLCdkcm9wYm94JzpOb25lLCdnb29nbGUnOk5vbmV9', max_length=100000000),
        ),
    ]
