# Generated by Django 4.2.6 on 2023-10-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_signup_key_alter_signup_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='image',
            field=models.ImageField(default='hacker.jpg', upload_to='images'),
        ),
    ]
